import { AppState } from './types';

export const seedData: AppState = {
  employees: [
    {
      id: 'emp-1',
      firstName: 'John',
      lastName: 'Smith',
      email: 'john.smith@company.com',
      phone: '+1-555-0101',
      department: 'Engineering',
      role: 'Senior Developer',
      hireDate: '2022-03-15',
      baseSalary: 95000,
      status: 'Active',
      bankName: 'First National Bank',
      bankAccountNo: '****1234',
    },
    {
      id: 'emp-2',
      firstName: 'Sarah',
      lastName: 'Johnson',
      email: 'sarah.johnson@company.com',
      phone: '+1-555-0102',
      department: 'Engineering',
      role: 'Tech Lead',
      hireDate: '2021-08-20',
      baseSalary: 110000,
      status: 'Active',
      bankName: 'City Bank',
      bankAccountNo: '****5678',
    },
    {
      id: 'emp-3',
      firstName: 'Michael',
      lastName: 'Brown',
      email: 'michael.brown@company.com',
      phone: '+1-555-0103',
      department: 'Operations',
      role: 'Operations Manager',
      hireDate: '2020-11-10',
      baseSalary: 85000,
      status: 'Active',
      bankName: 'Trust Bank',
      bankAccountNo: '****9012',
    },
    {
      id: 'emp-4',
      firstName: 'Emily',
      lastName: 'Davis',
      email: 'emily.davis@company.com',
      phone: '+1-555-0104',
      department: 'HR',
      role: 'HR Specialist',
      hireDate: '2023-01-05',
      baseSalary: 65000,
      status: 'Active',
      bankName: 'Community Bank',
      bankAccountNo: '****3456',
    },
    {
      id: 'emp-5',
      firstName: 'David',
      lastName: 'Wilson',
      email: 'david.wilson@company.com',
      phone: '+1-555-0105',
      department: 'Finance',
      role: 'Financial Analyst',
      hireDate: '2022-07-18',
      baseSalary: 72000,
      status: 'Active',
      bankName: 'Metro Bank',
      bankAccountNo: '****7890',
    },
    {
      id: 'emp-6',
      firstName: 'Lisa',
      lastName: 'Martinez',
      email: 'lisa.martinez@company.com',
      phone: '+1-555-0106',
      department: 'Engineering',
      role: 'Junior Developer',
      hireDate: '2023-09-01',
      baseSalary: 68000,
      status: 'Active',
      bankName: 'First National Bank',
      bankAccountNo: '****2468',
    },
    {
      id: 'emp-7',
      firstName: 'Robert',
      lastName: 'Taylor',
      email: 'robert.taylor@company.com',
      phone: '+1-555-0107',
      department: 'Operations',
      role: 'Operations Coordinator',
      hireDate: '2021-12-03',
      baseSalary: 55000,
      status: 'Inactive',
      bankName: 'Regional Bank',
      bankAccountNo: '****1357',
    },
    {
      id: 'emp-8',
      firstName: 'Amanda',
      lastName: 'Anderson',
      email: 'amanda.anderson@company.com',
      phone: '+1-555-0108',
      department: 'HR',
      role: 'HR Manager',
      hireDate: '2019-05-14',
      baseSalary: 88000,
      status: 'Active',
      bankName: 'City Bank',
      bankAccountNo: '****8024',
    },
    {
      id: 'emp-9',
      firstName: 'Christopher',
      lastName: 'Thomas',
      email: 'chris.thomas@company.com',
      phone: '+1-555-0109',
      department: 'Finance',
      role: 'Finance Manager',
      hireDate: '2020-02-28',
      baseSalary: 98000,
      status: 'Active',
      bankName: 'Trust Bank',
      bankAccountNo: '****9753',
    },
    {
      id: 'emp-10',
      firstName: 'Jessica',
      lastName: 'Garcia',
      email: 'jessica.garcia@company.com',
      phone: '+1-555-0110',
      department: 'Engineering',
      role: 'DevOps Engineer',
      hireDate: '2022-11-22',
      baseSalary: 87000,
      status: 'Active',
      bankName: 'Community Bank',
      bankAccountNo: '****4682',
    },
  ],
  payrollRuns: [
    {
      id: 'run-1',
      periodStart: '2024-12-01',
      periodEnd: '2024-12-31',
      payDate: '2025-01-05',
      status: 'Processed',
      employeeIds: ['emp-1', 'emp-2', 'emp-3', 'emp-4', 'emp-5', 'emp-6', 'emp-8', 'emp-9', 'emp-10'],
      notes: 'December 2024 payroll with holiday bonuses',
    },
    {
      id: 'run-2',
      periodStart: '2024-11-01',
      periodEnd: '2024-11-30',
      payDate: '2024-12-05',
      status: 'Processed',
      employeeIds: ['emp-1', 'emp-2', 'emp-3', 'emp-4', 'emp-5', 'emp-6', 'emp-8', 'emp-9', 'emp-10'],
    },
    {
      id: 'run-3',
      periodStart: '2025-01-01',
      periodEnd: '2025-01-31',
      payDate: '2025-02-05',
      status: 'Draft',
      employeeIds: ['emp-1', 'emp-2', 'emp-3', 'emp-4', 'emp-5', 'emp-6', 'emp-8', 'emp-9', 'emp-10'],
      notes: 'January 2025 payroll - draft',
    },
  ],
  payslips: [
    {
      id: 'payslip-run-1-emp-1',
      payrollRunId: 'run-1',
      employeeId: 'emp-1',
      earnings: [
        { type: 'Holiday Bonus', amount: 2000 },
        { type: 'Overtime', amount: 500 },
      ],
      deductions: [
        { type: 'Health Insurance', amount: 200 },
      ],
      grossPay: 97500,
      totalDeductions: 10150,
      netPay: 87350,
    },
    {
      id: 'payslip-run-1-emp-2',
      payrollRunId: 'run-1',
      employeeId: 'emp-2',
      earnings: [
        { type: 'Holiday Bonus', amount: 2500 },
      ],
      deductions: [
        { type: 'Health Insurance', amount: 250 },
        { type: 'Loan Repayment', amount: 300 },
      ],
      grossPay: 112500,
      totalDeductions: 11800,
      netPay: 100700,
    },
  ],
  departments: [
    { id: 'dept-1', name: 'Engineering' },
    { id: 'dept-2', name: 'Operations' },
    { id: 'dept-3', name: 'HR' },
    { id: 'dept-4', name: 'Finance' },
  ],
  roles: [
    { id: 'role-1', name: 'Junior Developer' },
    { id: 'role-2', name: 'Senior Developer' },
    { id: 'role-3', name: 'Tech Lead' },
    { id: 'role-4', name: 'DevOps Engineer' },
    { id: 'role-5', name: 'Operations Coordinator' },
    { id: 'role-6', name: 'Operations Manager' },
    { id: 'role-7', name: 'HR Specialist' },
    { id: 'role-8', name: 'HR Manager' },
    { id: 'role-9', name: 'Financial Analyst' },
    { id: 'role-10', name: 'Finance Manager' },
  ],
  earningTypes: [
    { id: 'earning-1', name: 'Base Salary' },
    { id: 'earning-2', name: 'Overtime' },
    { id: 'earning-3', name: 'Allowance' },
    { id: 'earning-4', name: 'Bonus' },
    { id: 'earning-5', name: 'Holiday Bonus' },
    { id: 'earning-6', name: 'Commission' },
  ],
  deductionTypes: [
    { id: 'deduction-1', name: 'Tax' },
    { id: 'deduction-2', name: 'Pension' },
    { id: 'deduction-3', name: 'Health Insurance' },
    { id: 'deduction-4', name: 'Loan Repayment' },
    { id: 'deduction-5', name: 'Union Dues' },
    { id: 'deduction-6', name: 'Parking' },
  ],
  useLocalStorage: true,
};